SistemaPueblito.Web/Controllers/ChildrenController.cs
namespace SistemaPueblito.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using SistemaPueblito.Web.Data.Entities;
    using SistemaPueblito.Web.Data.Repositories;
    using SistemaPueblito.Web.Helpers;
    using SistemaPueblito.Web.Models;
    using System;
    using System.IO;
    using System.Threading.Tasks;

    
    public class ChildrenController : Controller
    {
        private readonly IChildRepository childRepository;        
        private readonly IUserHelper userHelper;

        public ChildrenController(IChildRepository childRepository,            
            IUserHelper userHelper)
        {
            this.childRepository = childRepository;
            
            this.userHelper = userHelper;
        }        

        public IActionResult Index()
        {
            return View(this.childRepository.GetAll());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ChildNotFound");
            }

            var child = await this.childRepository.GetByIdAsync(id.Value);
            if (child == null)
            {
                return new NotFoundViewResult("ChildNotFound");
            }

            return View(child);
        }

        [Authorize(Roles ="Administrador")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ChildViewModel view)
        {
            if (ModelState.IsValid)
            {
                var path = string.Empty;

                if (view.ImageFile != null && view.ImageFile.Length > 0)
                {
                    var guid = Guid.NewGuid().ToString();
                    var file = $"{guid}.jpg";

                    path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\Children", file);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await view.ImageFile.CopyToAsync(stream);
                    }

                    path = $"~/images/Children/{file}";
                }

                view.User = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                var child = this.ToChild(view, path);
                await this.childRepository.CreateAsync(child);
                return RedirectToAction(nameof(Index));
            }

            return View(view);
        }

        private Child ToChild(ChildViewModel view, string path)
        {
            return new Child
            {
                Id = view.Id,
                ImageUrl = path,
                Age = view.Age,
                BirthDate = view.BirthDate,
                FirstName = view.FirstName,
                LastName = view.LastName,
                User = view.User
            };
        }

        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ChildNotFound");
            }

            var child = await this.childRepository.GetByIdAsync(id.Value);
            if (child == null)
            {
                return new NotFoundViewResult("ChildNotFound");
            }

            var view = this.ToChildViewModel(child);
            return View(view);
        }

        private ChildViewModel ToChildViewModel(Child child)
        {
            return new ChildViewModel
            {
                Id = child.Id,
                ImageUrl = child.ImageUrl,
                Age = child.Age,
                BirthDate = child.BirthDate,
                FirstName = child.FirstName,
                LastName = child.LastName,
                User = child.User,
            };
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ChildViewModel view)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var path = view.ImageUrl;

                    if (view.ImageFile != null && view.ImageFile.Length > 0)
                    {
                        var guid = Guid.NewGuid().ToString();
                        var file = $"{guid}.jpg";

                        path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\Children", file);

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await view.ImageFile.CopyToAsync(stream);
                        }

                        path = $"~/images/Children/{file}";
                    }

                    view.User = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                    var child = this.ToChild(view, path);
                    await this.childRepository.UpdateAsync(child);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.childRepository.ExistAsync(view.Id))
                    {
                        return new NotFoundViewResult("ChildNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(view);
        }

        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ChildNotFound");
            }

            var child = await this.childRepository.GetByIdAsync(id.Value);
            if (child == null)
            {
                return new NotFoundViewResult("ChildNotFound");
            }

            return View(child);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var child = await this.childRepository.GetByIdAsync(id);
            await this.childRepository.DeleteAsync(child);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ChildNotFound()
        {
            return this.View();
        }
    }
}

SistemaPueblito.Web/Controllers/HousesController.cs
namespace SistemaPueblito.Web.Controllers
{
    using Data.Entities;
    using Data.Repositories;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using SistemaPueblito.Web.Helpers;
    using System.Threading.Tasks;

    
    public class HousesController : Controller
    {
        private readonly IHouseRepository houseRepository;
        private readonly IUserHelper userHelper;

        public HousesController(IHouseRepository houseRepository, IUserHelper userHelper)
        {
            this.houseRepository = houseRepository;
            this.userHelper = userHelper;
        }

        // GET: Houses
        public IActionResult Index()
        {
            return View(this.houseRepository.GetAll());
        }

        // GET: Houses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("HouseNotFound");
            }

            var house = await this.houseRepository.GetByIdAsync(id.Value);
            if (house == null)
            {
                return new NotFoundViewResult("HouseNotFound");
            }

            return View(house);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Houses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Houses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(House house)
        {
            if (ModelState.IsValid)
            {                
                house.User = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                await this.houseRepository.CreateAsync(house);
                return RedirectToAction(nameof(Index));
            }
            return View(house);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Houses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("HouseNotFound");
            }

            var house = await this.houseRepository.GetByIdAsync(id.Value);
            if (house == null)
            {
                return new NotFoundViewResult("HouseNotFound");
            }
            return View(house);
        }

        // POST: Houses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(House house)
        {

            if (ModelState.IsValid)
            {
                try
                {                    
                    house.User = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                    await this.houseRepository.UpdateAsync(house);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.houseRepository.ExistAsync(house.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(house);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Houses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("HouseNotFound");
            }

            var house = await this.houseRepository.GetByIdAsync(id.Value);
            if (house == null)
            {
                return new NotFoundViewResult("HouseNotFound");
            }

            return View(house);
        }

        // POST: Houses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var house = await this.houseRepository.GetByIdAsync(id);
            await this.houseRepository.DeleteAsync(house);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult HouseNotFound()
        {
            return this.View();
        }


    }
}

SistemaPueblito.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaPueblito.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img src="~/images/Logo Pueblito 2019.jpg" style="width:100px;height:150px;max-width:100%;height:auto;"/>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Acerca de</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contacto</a></li>
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Houses" asp-action="Index">Casas</a></li>
                        <li><a asp-area="" asp-controller="Children" asp-action="Index">Niños</a></li>
                        @if (this.User.IsInRole("Administrador"))
                        {
                            <li><a asp-area="" asp-controller="Account" asp-action="Index">Usuarios</a></li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>

            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - SistemaPueblito.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>